//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTrack.For.ReSharper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTrack.For.ReSharper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap issue_high_priority {
            get {
                object obj = ResourceManager.GetObject("issue_high_priority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap issue_low_priority {
            get {
                object obj = ResourceManager.GetObject("issue_low_priority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap youtrack_logo {
            get {
                object obj = ResourceManager.GetObject("youtrack_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap youtrack_logo1 {
            get {
                object obj = ResourceManager.GetObject("youtrack_logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap youtrack_root {
            get {
                object obj = ResourceManager.GetObject("youtrack_root", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string YouTrackIssueViewInitializeDescription {
            get {
                return ResourceManager.GetString("YouTrackIssueViewInitializeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string YouTrackIssueViewInitializeSummary {
            get {
                return ResourceManager.GetString("YouTrackIssueViewInitializeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a solution open.
        /// </summary>
        internal static string YouTrackSearchActionExecuteYouNeedASolutionOpen {
            get {
                return ResourceManager.GetString("YouTrackSearchActionExecuteYouNeedASolutionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTrack Settings.
        /// </summary>
        internal static string YouTrackSettingsFormYouTrackSettings {
            get {
                return ResourceManager.GetString("YouTrackSettingsFormYouTrackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host and Project are required.
        /// </summary>
        internal static string YouTrackSettingsValidateSettingsHostAndProjectARequired {
            get {
                return ResourceManager.GetString("YouTrackSettingsValidateSettingsHostAndProjectARequired", resourceCulture);
            }
        }
    }
}
